Las features y el nombre del archivo donde se guardan los resultados están hardcodeadas en el archivo model.py y main.py (perdón por eso)

In [1]:
# Cambiar el directorio de trabajo a la carpeta de SASRec
%cd SASRec.pytorch/python

# Ejecutar el entrenamiento usando el nuevo txt generado
!python main.py --dataset=interaction_resumen --train_dir=mis_resultados --maxlen=200 --hidden_units=64 --dropout_rate=0.2 --device=cuda --num_epochs=100

# Volver al directorio original
%cd ../..

/home/equipo/Documentos/Documentos_UC/6to_ano_1er_semestre/Sistemas_Recomendadores/repo_proyecto/recsys-pf/notebooks/SASRec.pytorch/python
average sequence length: 2.79

[!] Éxito: Pesos de items cargados desde 'embeddings_efmrec_gated.pt'
loss in epoch 1 iteration 0: 1.3901238441467285
loss in epoch 1 iteration 1: 1.3909448385238647
loss in epoch 1 iteration 2: 1.3863232135772705
loss in epoch 1 iteration 3: 1.3862390518188477
loss in epoch 1 iteration 4: 1.3806514739990234
loss in epoch 1 iteration 5: 1.3848154544830322
loss in epoch 1 iteration 6: 1.3789674043655396
loss in epoch 1 iteration 7: 1.3705973625183105
loss in epoch 1 iteration 8: 1.3819748163223267
loss in epoch 1 iteration 9: 1.3784431219100952
loss in epoch 1 iteration 10: 1.3715977668762207
loss in epoch 1 iteration 11: 1.3739997148513794
loss in epoch 1 iteration 12: 1.3755271434783936
loss in epoch 1 iteration 13: 1.3719217777252197
loss in epoch 1 iteration 14: 1.3688952922821045
loss in epoch 1 iteration 15: 1.3693740367889404
loss in epoch 1 iteration 16: 1.364683985710144
loss in epoch 1 iteration 17: 1.3642122745513916
loss in epoch 1 iteration 18: 1.3715460300445557
loss in epoch 1 iteration 19: 1.3589439392089844
loss in epoch 1 iteration 20: 1.3724899291992188
loss in epoch 1 iteration 21: 1.3513154983520508
loss in epoch 1 iteration 22: 1.3586962223052979
loss in epoch 1 iteration 23: 1.3471615314483643
loss in epoch 1 iteration 24: 1.353908658027649
loss in epoch 1 iteration 25: 1.3438503742218018
loss in epoch 1 iteration 26: 1.3462672233581543
loss in epoch 1 iteration 27: 1.3329380750656128
loss in epoch 1 iteration 28: 1.341658115386963
loss in epoch 1 iteration 29: 1.3489837646484375
loss in epoch 1 iteration 30: 1.3489540815353394
loss in epoch 1 iteration 31: 1.3247416019439697
loss in epoch 1 iteration 32: 1.33026921749115
loss in epoch 1 iteration 33: 1.3269517421722412
loss in epoch 1 iteration 34: 1.3250879049301147
loss in epoch 1 iteration 35: 1.3119065761566162
loss in epoch 1 iteration 36: 1.3157018423080444
loss in epoch 1 iteration 37: 1.315115213394165
loss in epoch 1 iteration 38: 1.3283207416534424
loss in epoch 1 iteration 39: 1.3128528594970703
loss in epoch 1 iteration 40: 1.2919819355010986
loss in epoch 1 iteration 41: 1.3096966743469238
loss in epoch 1 iteration 42: 1.3090035915374756
loss in epoch 1 iteration 43: 1.2975271940231323
loss in epoch 1 iteration 44: 1.302080512046814
loss in epoch 1 iteration 45: 1.310365915298462
loss in epoch 1 iteration 46: 1.3195629119873047
loss in epoch 1 iteration 47: 1.3108105659484863
loss in epoch 1 iteration 48: 1.2848899364471436
loss in epoch 1 iteration 49: 1.2948133945465088
loss in epoch 1 iteration 50: 1.299464225769043
loss in epoch 1 iteration 51: 1.2862902879714966
loss in epoch 1 iteration 52: 1.2939260005950928
loss in epoch 1 iteration 53: 1.2944934368133545
loss in epoch 1 iteration 54: 1.3073575496673584
loss in epoch 1 iteration 55: 1.2721893787384033
loss in epoch 1 iteration 56: 1.2669036388397217
loss in epoch 1 iteration 57: 1.2728631496429443
loss in epoch 1 iteration 58: 1.2700687646865845
loss in epoch 1 iteration 59: 1.263325572013855
loss in epoch 1 iteration 60: 1.275604009628296
loss in epoch 1 iteration 61: 1.2461585998535156
loss in epoch 1 iteration 62: 1.2492539882659912
loss in epoch 1 iteration 63: 1.2624140977859497
loss in epoch 1 iteration 64: 1.2365620136260986
loss in epoch 1 iteration 65: 1.2766952514648438
loss in epoch 1 iteration 66: 1.2328379154205322
loss in epoch 1 iteration 67: 1.2353131771087646
loss in epoch 1 iteration 68: 1.2415740489959717
loss in epoch 1 iteration 69: 1.2428921461105347
loss in epoch 1 iteration 70: 1.2353781461715698
loss in epoch 1 iteration 71: 1.2546212673187256
loss in epoch 1 iteration 72: 1.2438502311706543
loss in epoch 1 iteration 73: 1.2467726469039917
loss in epoch 1 iteration 74: 1.2221388816833496
loss in epoch 1 iteration 75: 1.2260334491729736
loss in epoch 1 iteration 76: 1.2373712062835693
loss in epoch 1 iteration 77: 1.2037822008132935
loss in epoch 1 iteration 78: 1.246753454208374
loss in epoch 1 iteration 79: 1.2397819757461548
loss in epoch 1 iteration 80: 1.2275103330612183
loss in epoch 1 iteration 81: 1.2610435485839844
loss in epoch 1 iteration 82: 1.2089006900787354
loss in epoch 1 iteration 83: 1.2259409427642822
loss in epoch 1 iteration 84: 1.1901216506958008
loss in epoch 1 iteration 85: 1.2138426303863525
loss in epoch 1 iteration 86: 1.2072372436523438
loss in epoch 1 iteration 87: 1.22490394115448
loss in epoch 1 iteration 88: 1.188923954963684
loss in epoch 1 iteration 89: 1.2010626792907715
loss in epoch 1 iteration 90: 1.2206236124038696
loss in epoch 1 iteration 91: 1.178084135055542
loss in epoch 1 iteration 92: 1.1891356706619263
loss in epoch 1 iteration 93: 1.1605721712112427
loss in epoch 1 iteration 94: 1.2028766870498657
loss in epoch 1 iteration 95: 1.1945942640304565
loss in epoch 1 iteration 96: 1.1777656078338623
loss in epoch 1 iteration 97: 1.2383151054382324
loss in epoch 1 iteration 98: 1.1672872304916382
loss in epoch 1 iteration 99: 1.2195130586624146
loss in epoch 1 iteration 100: 1.196366548538208
loss in epoch 1 iteration 101: 1.1941463947296143
loss in epoch 1 iteration 102: 1.1864912509918213
loss in epoch 1 iteration 103: 1.1695934534072876
loss in epoch 1 iteration 104: 1.2383253574371338
loss in epoch 1 iteration 105: 1.1435770988464355
loss in epoch 1 iteration 106: 1.2130986452102661
loss in epoch 1 iteration 107: 1.194692850112915
loss in epoch 1 iteration 108: 1.1666492223739624
loss in epoch 1 iteration 109: 1.1783682107925415
loss in epoch 1 iteration 110: 1.1634453535079956
loss in epoch 1 iteration 111: 1.1655861139297485
loss in epoch 1 iteration 112: 1.1422016620635986
loss in epoch 1 iteration 113: 1.2106479406356812
loss in epoch 1 iteration 114: 1.170282244682312
loss in epoch 1 iteration 115: 1.1497509479522705
loss in epoch 1 iteration 116: 1.1899006366729736
loss in epoch 1 iteration 117: 1.2126507759094238
loss in epoch 1 iteration 118: 1.1647751331329346
loss in epoch 1 iteration 119: 1.1908109188079834
loss in epoch 1 iteration 120: 1.13619863986969
loss in epoch 1 iteration 121: 1.1584358215332031
loss in epoch 1 iteration 122: 1.1943604946136475
loss in epoch 1 iteration 123: 1.185473918914795
loss in epoch 1 iteration 124: 1.1560157537460327
loss in epoch 1 iteration 125: 1.1238338947296143
loss in epoch 1 iteration 126: 1.154619812965393
loss in epoch 1 iteration 127: 1.140995979309082
loss in epoch 1 iteration 128: 1.095656156539917
loss in epoch 1 iteration 129: 1.1793036460876465
loss in epoch 1 iteration 130: 1.193064570426941
loss in epoch 1 iteration 131: 1.1450529098510742
loss in epoch 1 iteration 132: 1.151151418685913
loss in epoch 1 iteration 133: 1.1644690036773682
loss in epoch 1 iteration 134: 1.123473048210144
loss in epoch 1 iteration 135: 1.135462999343872
loss in epoch 1 iteration 136: 1.1725302934646606
loss in epoch 1 iteration 137: 1.1566205024719238
loss in epoch 1 iteration 138: 1.123960256576538
loss in epoch 1 iteration 139: 1.1378984451293945
loss in epoch 1 iteration 140: 1.128761649131775
loss in epoch 1 iteration 141: 1.1655254364013672
loss in epoch 1 iteration 142: 1.1468496322631836
loss in epoch 1 iteration 143: 1.0941991806030273
loss in epoch 1 iteration 144: 1.1834920644760132
loss in epoch 1 iteration 145: 1.1384960412979126
loss in epoch 1 iteration 146: 1.1890298128128052
loss in epoch 1 iteration 147: 1.159793734550476
loss in epoch 1 iteration 148: 1.2136517763137817
loss in epoch 1 iteration 149: 1.1231316328048706
loss in epoch 1 iteration 150: 1.1204710006713867
loss in epoch 1 iteration 151: 1.130805492401123
loss in epoch 1 iteration 152: 1.1424436569213867
loss in epoch 1 iteration 153: 1.127619981765747
loss in epoch 1 iteration 154: 1.1735241413116455
loss in epoch 1 iteration 155: 1.1547757387161255
loss in epoch 1 iteration 156: 1.171318769454956
loss in epoch 1 iteration 157: 1.1132532358169556
loss in epoch 1 iteration 158: 1.1132545471191406
loss in epoch 1 iteration 159: 1.1424455642700195
loss in epoch 1 iteration 160: 1.1189725399017334
loss in epoch 1 iteration 161: 1.0962353944778442
loss in epoch 1 iteration 162: 1.0923728942871094
loss in epoch 1 iteration 163: 1.0885579586029053
loss in epoch 1 iteration 164: 1.1409088373184204
loss in epoch 1 iteration 165: 1.1564977169036865
loss in epoch 1 iteration 166: 1.128692388534546
loss in epoch 1 iteration 167: 1.0533242225646973
loss in epoch 1 iteration 168: 1.0566601753234863
loss in epoch 1 iteration 169: 1.091007947921753
loss in epoch 1 iteration 170: 1.112847924232483
loss in epoch 1 iteration 171: 1.0447932481765747
loss in epoch 1 iteration 172: 1.1394747495651245
loss in epoch 1 iteration 173: 1.152825117111206
loss in epoch 1 iteration 174: 1.1003568172454834
loss in epoch 1 iteration 175: 1.1478769779205322
loss in epoch 1 iteration 176: 1.1298582553863525
loss in epoch 1 iteration 177: 1.12710440158844
loss in epoch 1 iteration 178: 1.140570044517517
loss in epoch 1 iteration 179: 1.0411790609359741
loss in epoch 1 iteration 180: 1.134524941444397
loss in epoch 1 iteration 181: 1.1409339904785156
loss in epoch 1 iteration 182: 1.07570219039917
loss in epoch 1 iteration 183: 1.0913887023925781
loss in epoch 1 iteration 184: 1.0456150770187378
loss in epoch 1 iteration 185: 1.1135307550430298
loss in epoch 1 iteration 186: 1.0871739387512207
loss in epoch 1 iteration 187: 1.1212002038955688
loss in epoch 1 iteration 188: 1.0370807647705078
loss in epoch 1 iteration 189: 1.0769973993301392
loss in epoch 1 iteration 190: 1.149745225906372
loss in epoch 1 iteration 191: 1.141702651977539
loss in epoch 1 iteration 192: 1.1088414192199707
loss in epoch 1 iteration 193: 1.1107832193374634
loss in epoch 1 iteration 194: 1.0284184217453003
loss in epoch 1 iteration 195: 1.0661869049072266
loss in epoch 1 iteration 196: 1.1168607473373413
loss in epoch 1 iteration 197: 1.103118658065796
loss in epoch 1 iteration 198: 1.0981934070587158
loss in epoch 1 iteration 199: 1.0844264030456543
loss in epoch 1 iteration 200: 1.1566448211669922
loss in epoch 1 iteration 201: 1.1169413328170776
loss in epoch 1 iteration 202: 1.1555860042572021
loss in epoch 1 iteration 203: 1.046642780303955
loss in epoch 1 iteration 204: 1.0764780044555664
loss in epoch 1 iteration 205: 1.05436372756958
loss in epoch 1 iteration 206: 1.1269569396972656
loss in epoch 1 iteration 207: 1.1714632511138916
loss in epoch 1 iteration 208: 1.12395179271698
loss in epoch 1 iteration 209: 1.0777910947799683
loss in epoch 1 iteration 210: 1.068355679512024
loss in epoch 1 iteration 211: 1.1306666135787964
loss in epoch 1 iteration 212: 1.0906611680984497
loss in epoch 1 iteration 213: 1.0762736797332764
loss in epoch 1 iteration 214: 1.0791423320770264
loss in epoch 1 iteration 215: 1.0862858295440674
loss in epoch 1 iteration 216: 1.0984368324279785
loss in epoch 1 iteration 217: 1.1448067426681519
loss in epoch 1 iteration 218: 1.045690894126892
loss in epoch 1 iteration 219: 1.0772770643234253
loss in epoch 1 iteration 220: 1.0991050004959106
loss in epoch 1 iteration 221: 1.1050008535385132
loss in epoch 1 iteration 222: 1.084640622138977
loss in epoch 1 iteration 223: 1.0530977249145508
loss in epoch 1 iteration 224: 1.1010923385620117
loss in epoch 1 iteration 225: 1.0950212478637695
loss in epoch 1 iteration 226: 1.0803778171539307
loss in epoch 1 iteration 227: 1.099360704421997
loss in epoch 1 iteration 228: 1.1090710163116455
loss in epoch 1 iteration 229: 1.0531625747680664
loss in epoch 1 iteration 230: 1.0027399063110352
loss in epoch 1 iteration 231: 1.051931619644165
loss in epoch 1 iteration 232: 1.097791075706482
loss in epoch 1 iteration 233: 1.0850999355316162
loss in epoch 1 iteration 234: 1.1480768918991089
loss in epoch 1 iteration 235: 1.093247890472412
loss in epoch 1 iteration 236: 1.0533392429351807
loss in epoch 1 iteration 237: 1.1402865648269653
loss in epoch 1 iteration 238: 1.021705985069275
loss in epoch 1 iteration 239: 1.0932081937789917
loss in epoch 1 iteration 240: 1.0594077110290527
loss in epoch 1 iteration 241: 1.0454823970794678
loss in epoch 1 iteration 242: 1.0436668395996094
loss in epoch 1 iteration 243: 1.1425741910934448
loss in epoch 1 iteration 244: 1.0153746604919434
loss in epoch 1 iteration 245: 1.1251764297485352
loss in epoch 1 iteration 246: 1.0277293920516968
loss in epoch 1 iteration 247: 1.074021816253662
loss in epoch 1 iteration 248: 1.039200782775879
loss in epoch 1 iteration 249: 1.0807700157165527
loss in epoch 1 iteration 250: 1.0957581996917725
loss in epoch 1 iteration 251: 1.0559287071228027
loss in epoch 1 iteration 252: 1.1128969192504883
loss in epoch 1 iteration 253: 1.0438356399536133
loss in epoch 1 iteration 254: 1.0872454643249512
loss in epoch 1 iteration 255: 1.042372465133667
loss in epoch 1 iteration 256: 1.1475433111190796
loss in epoch 1 iteration 257: 1.1987882852554321
loss in epoch 1 iteration 258: 1.0393624305725098
loss in epoch 1 iteration 259: 0.9950732588768005
loss in epoch 1 iteration 260: 1.1124939918518066
loss in epoch 1 iteration 261: 1.0796266794204712
loss in epoch 1 iteration 262: 1.0561554431915283
loss in epoch 1 iteration 263: 1.086171269416809
loss in epoch 1 iteration 264: 1.083457112312317
loss in epoch 1 iteration 265: 1.137568712234497
loss in epoch 1 iteration 266: 1.0895863771438599
loss in epoch 1 iteration 267: 1.049857258796692
loss in epoch 1 iteration 268: 1.1225364208221436
loss in epoch 1 iteration 269: 1.0540380477905273
loss in epoch 1 iteration 270: 1.1451616287231445
loss in epoch 1 iteration 271: 1.143460988998413
loss in epoch 1 iteration 272: 1.0673514604568481
loss in epoch 1 iteration 273: 1.0072922706604004
loss in epoch 1 iteration 274: 1.123893141746521
loss in epoch 1 iteration 275: 1.0228300094604492
loss in epoch 1 iteration 276: 1.0599164962768555
loss in epoch 1 iteration 277: 1.0644209384918213
loss in epoch 1 iteration 278: 1.0706470012664795
loss in epoch 1 iteration 279: 1.0399277210235596
loss in epoch 1 iteration 280: 1.0681307315826416
loss in epoch 1 iteration 281: 1.1216135025024414
loss in epoch 1 iteration 282: 1.0737574100494385
loss in epoch 1 iteration 283: 1.0775628089904785
loss in epoch 1 iteration 284: 1.089652419090271
loss in epoch 1 iteration 285: 1.1041773557662964
loss in epoch 1 iteration 286: 1.0853431224822998
loss in epoch 1 iteration 287: 1.035372018814087
loss in epoch 1 iteration 288: 1.157679796218872
loss in epoch 1 iteration 289: 1.1245613098144531
loss in epoch 1 iteration 290: 1.0691133737564087
loss in epoch 1 iteration 291: 1.068067193031311
loss in epoch 1 iteration 292: 1.0978046655654907
loss in epoch 1 iteration 293: 1.073021411895752
loss in epoch 1 iteration 294: 1.1482962369918823
loss in epoch 1 iteration 295: 1.1237776279449463
loss in epoch 1 iteration 296: 1.1085888147354126
loss in epoch 1 iteration 297: 1.0838866233825684
loss in epoch 1 iteration 298: 1.1204988956451416
loss in epoch 1 iteration 299: 1.061835765838623
loss in epoch 1 iteration 300: 1.0148441791534424
loss in epoch 1 iteration 301: 1.022493600845337
loss in epoch 1 iteration 302: 1.0736910104751587
loss in epoch 1 iteration 303: 0.9665805101394653
loss in epoch 1 iteration 304: 1.1289805173873901
loss in epoch 1 iteration 305: 1.0226728916168213
loss in epoch 1 iteration 306: 1.0164225101470947
loss in epoch 1 iteration 307: 1.113226294517517
loss in epoch 1 iteration 308: 1.0838890075683594
loss in epoch 1 iteration 309: 0.9594747424125671
loss in epoch 1 iteration 310: 1.0819523334503174
loss in epoch 1 iteration 311: 1.0341969728469849
loss in epoch 1 iteration 312: 1.0388712882995605
loss in epoch 1 iteration 313: 1.1323648691177368
loss in epoch 1 iteration 314: 1.069566011428833
loss in epoch 1 iteration 315: 1.0244381427764893
loss in epoch 1 iteration 316: 1.0400340557098389
loss in epoch 1 iteration 317: 1.0782232284545898
loss in epoch 1 iteration 318: 1.1072626113891602
loss in epoch 1 iteration 319: 1.0615406036376953
loss in epoch 1 iteration 320: 1.017638087272644
loss in epoch 1 iteration 321: 1.1205512285232544
loss in epoch 1 iteration 322: 1.0094797611236572
loss in epoch 1 iteration 323: 1.0670676231384277
loss in epoch 1 iteration 324: 1.0358448028564453
loss in epoch 1 iteration 325: 1.0239434242248535
loss in epoch 1 iteration 326: 1.0257306098937988
loss in epoch 1 iteration 327: 1.0868479013442993
loss in epoch 1 iteration 328: 1.0636732578277588
loss in epoch 1 iteration 329: 1.0423802137374878
loss in epoch 1 iteration 330: 0.9990318417549133
loss in epoch 1 iteration 331: 1.1173917055130005
loss in epoch 1 iteration 332: 1.0344173908233643
loss in epoch 1 iteration 333: 1.0791674852371216
loss in epoch 1 iteration 334: 1.0712897777557373
loss in epoch 1 iteration 335: 1.0407181978225708
loss in epoch 1 iteration 336: 1.1129467487335205
loss in epoch 1 iteration 337: 1.0501683950424194
loss in epoch 1 iteration 338: 1.1209672689437866
loss in epoch 2 iteration 0: 1.0324749946594238
loss in epoch 2 iteration 1: 0.9609637260437012
loss in epoch 2 iteration 2: 1.0139731168746948
loss in epoch 2 iteration 3: 1.0997635126113892
loss in epoch 2 iteration 4: 1.0114290714263916
loss in epoch 2 iteration 5: 1.010845422744751
loss in epoch 2 iteration 6: 1.0212041139602661
loss in epoch 2 iteration 7: 1.0508861541748047
loss in epoch 2 iteration 8: 1.053117036819458
loss in epoch 2 iteration 9: 1.0878775119781494
loss in epoch 2 iteration 10: 1.0478593111038208
loss in epoch 2 iteration 11: 1.0642632246017456
loss in epoch 2 iteration 12: 1.085767149925232
loss in epoch 2 iteration 13: 0.9800200462341309
loss in epoch 2 iteration 14: 1.026106357574463
loss in epoch 2 iteration 15: 0.9248857498168945
loss in epoch 2 iteration 16: 0.9959398508071899
loss in epoch 2 iteration 17: 1.021756887435913
loss in epoch 2 iteration 18: 1.0645039081573486
loss in epoch 2 iteration 19: 1.085874319076538
loss in epoch 2 iteration 20: 0.9631611108779907
loss in epoch 2 iteration 21: 0.9853314161300659
loss in epoch 2 iteration 22: 1.0946283340454102
loss in epoch 2 iteration 23: 1.008113145828247
loss in epoch 2 iteration 24: 1.0183398723602295
loss in epoch 2 iteration 25: 1.064087152481079
loss in epoch 2 iteration 26: 1.0554628372192383
loss in epoch 2 iteration 27: 1.0063679218292236
loss in epoch 2 iteration 28: 1.0402722358703613
loss in epoch 2 iteration 29: 1.0927996635437012
loss in epoch 2 iteration 30: 1.036064863204956
loss in epoch 2 iteration 31: 1.0525035858154297
loss in epoch 2 iteration 32: 1.0320523977279663
loss in epoch 2 iteration 33: 1.0642107725143433
loss in epoch 2 iteration 34: 0.9971721172332764
loss in epoch 2 iteration 35: 1.1006200313568115
loss in epoch 2 iteration 36: 1.0831520557403564
loss in epoch 2 iteration 37: 1.0331776142120361
loss in epoch 2 iteration 38: 1.0708565711975098
loss in epoch 2 iteration 39: 1.0244317054748535
loss in epoch 2 iteration 40: 1.0053789615631104
loss in epoch 2 iteration 41: 0.9672985076904297
loss in epoch 2 iteration 42: 1.0135674476623535
loss in epoch 2 iteration 43: 0.9997580051422119
loss in epoch 2 iteration 44: 1.0170530080795288
loss in epoch 2 iteration 45: 1.0795159339904785
loss in epoch 2 iteration 46: 1.062476634979248
loss in epoch 2 iteration 47: 1.0504693984985352
loss in epoch 2 iteration 48: 1.0850625038146973
loss in epoch 2 iteration 49: 0.9585022330284119
loss in epoch 2 iteration 50: 0.9181362986564636
loss in epoch 2 iteration 51: 0.9969772696495056
loss in epoch 2 iteration 52: 0.9884473085403442
loss in epoch 2 iteration 53: 1.0840094089508057
loss in epoch 2 iteration 54: 1.0160412788391113
loss in epoch 2 iteration 55: 0.9895772933959961
loss in epoch 2 iteration 56: 0.9955042004585266
loss in epoch 2 iteration 57: 1.0514057874679565
loss in epoch 2 iteration 58: 1.05701744556427
loss in epoch 2 iteration 59: 0.9469802379608154
loss in epoch 2 iteration 60: 1.0386722087860107

# Evaluar resultados

In [2]:
import os
import pandas as pd
from PIL import Image
import matplotlib.pyplot as plt
import glob
import gdown
import zipfile
import torch
import torch.nn as nn
from transformers import CLIPProcessor, CLIPModel
from torch.utils.data import Dataset, DataLoader
from tqdm.auto import tqdm
import numpy as np
import scipy.sparse as sp
import torch.optim as optim
import random
import torch.nn.functional as F
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity
from IPython.display import display
import copy
import gc
import json

device = "cuda" if torch.cuda.is_available() else "cpu"

/home/equipo/Documentos/Documentos_UC/6to_ano_1er_semestre/Sistemas_Recomendadores/recomendadores/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1782661138.913794    9176 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1782661138.958972    9176 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/home/equipo/Documentos/Documentos_UC/6to_ano_1er_semestre/Sistemas_Recomendadores/recomendadores/lib/python3.12/site-packages/tensorflow/python/keras/engine/training_arrays_v1.py:37: UserWarning: A NumPy version >=1.26.4 and <2.7.0 is required for this version of SciPy (detected version 1.26.0)
  from scipy.sparse import issparse  # pylint: disable=g-import-not-at-top
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1782661140.894347    9176 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

In [3]:
# cargar datos
interaction_df = pd.read_csv('recsys-pf/interaction.csv')
item_info_df = pd.read_csv('recsys-pf/item_info.csv')
item_info_df = item_info_df.dropna()

n_items_to_sample = 15000
sampled_item_info_df = item_info_df.sample(n=n_items_to_sample, random_state=5)

valid_item_ids = sampled_item_info_df['item_id'].unique()

sampled_interaction_df = interaction_df[interaction_df['item_id'].isin(valid_item_ids)]

image_folder = 'recsys-pf/resized_images'
valid_image_paths = [os.path.join(image_folder, f"{item_id}.jpg") for item_id in valid_item_ids]

print(f"Sampled items: {len(sampled_item_info_df)}")
print(f"Sampled interactions: {len(sampled_interaction_df)}")
print(f"Number of valid image paths: {len(valid_image_paths)}")

sampled_interaction_df.loc[:, 'user_id'] = sampled_interaction_df['user_id'].astype('category').cat.codes
sampled_interaction_df.loc[:, 'item_id'] = sampled_interaction_df['item_id'].astype('category').cat.codes

num_users = sampled_interaction_df['user_id'].nunique()
num_items = sampled_interaction_df['item_id'].nunique()

sampled_interaction_df = sampled_interaction_df.sort_values('timestamp')
total_rows = len(sampled_interaction_df)
train_split_idx = int(total_rows * 0.80)
val_split_idx = int(total_rows * 0.90)
train_df = sampled_interaction_df.iloc[:train_split_idx].copy()
val_df = sampled_interaction_df.iloc[train_split_idx:val_split_idx].copy()
test_df = sampled_interaction_df.iloc[val_split_idx:].copy()

train_df['user_id'] = train_df['user_id'].astype(int)
train_df['item_id'] = train_df['item_id'].astype(int)
val_df['user_id'] = val_df['user_id'].astype(int)
val_df['item_id'] = val_df['item_id'].astype(int)
test_df['user_id'] = test_df['user_id'].astype(int)
test_df['item_id'] = test_df['item_id'].astype(int)

Sampled items: 15000
Sampled interactions: 188108
Number of valid image paths: 15000

In [ ]:
# Modifcar interacciones para SASRec
# Debe ser un archivo txt, con solo dos números (user_id item_id) separados por espacio ordenados cronologicamente por usuario (que asumo ya se hizo)

df_sasrec = train_df[['user_id', 'item_id']].copy()

usuarios_unicos = df_sasrec['user_id'].unique()
user2id_denso = {user: i + 1 for i, user in enumerate(usuarios_unicos)}
id2user_original = {i + 1: user for i, user in enumerate(usuarios_unicos)}

df_sasrec['user_id'] = df_sasrec['user_id'].map(user2id_denso)
df_sasrec['item_id'] = df_sasrec['item_id'] + 1

ruta_salida = 'SASRec.pytorch/python/data'
os.makedirs(ruta_salida, exist_ok=True)
ruta_txt = os.path.join(ruta_salida, 'interaction_resumen.txt')

df_sasrec.sort_values(by=['user_id', 'item_id']).to_csv(ruta_txt, sep=' ', index=False, header=False)
print(f"Se guardaron las interacciones para SASRec en: {ruta_txt}")

In [ ]:
id2user_original_json = {int(k): int(v) for k, v in id2user_original.items()}

ruta_json = os.path.join(ruta_salida, 'mapa_usuarios.json')
with open(ruta_json, 'w') as f:
    json.dump(id2user_original_json, f)

print(f"Diccionario de usuarios para evaluación: {ruta_json}")

In [4]:
# De práctico_métricas.ipynb
def precision_at_k(r, k):
    assert 1 <= k <= r.size
    return (np.asarray(r)[:k] != 0).mean()

def average_precision_at_k(r, k):
    r = np.asarray(r)
    score = 0.
    for i in range(min(k, r.size)):
        score += precision_at_k(r, i + 1)
    return score / k

def dcg_at_k(r, k):
    r = np.asarray(r)[:k]
    if r.size:
        return np.sum(np.subtract(np.power(2, r), 1) / np.log2(np.arange(2, r.size + 2)))
    return 0.

def idcg_at_k(k):
    return dcg_at_k(np.ones(k), k)

def ndcg_at_k(r, k, max_relevant):
    idcg = idcg_at_k(min(k, max_relevant))
    if not idcg:
        return 0.
    return dcg_at_k(r, k) / idcg

def recall_at_k(relevant_items, recommended_items, k):
    relevant_items = set(relevant_items)
    recommended_items = set(recommended_items[:k])
    intersection = relevant_items.intersection(recommended_items)
    recall = len(intersection) / len(relevant_items) if len(relevant_items) > 0 else 0
    return recall

def evaluate_model(y_true, y_pred, N):
    map_scores = 0.
    ndcg_scores = 0.
    recall_scores = 0.
    
    for true_items, pred_items in zip(y_true, y_pred):
        
        true_set = set(true_items)
        
        # el relevance vector
        r = [1 if item in true_set else 0 for item in pred_items]
        
        # MAP
        user_map = average_precision_at_k(r, N)
        map_scores += user_map
        # NDGC@N
        max_relevant = len(true_items)
        user_ndcg = ndcg_at_k(r, N, max_relevant)
        ndcg_scores += user_ndcg
        # Recall@N
        user_recall = recall_at_k(true_items, pred_items, N)
        recall_scores += user_recall
        
    cantidad = len(y_true)
    final_map = map_scores / cantidad
    final_ndcg = ndcg_scores / cantidad
    final_recall = recall_scores / cantidad
    
    print(f"Métricas de evaluación ranking (Top-{N}):")
    print(f"MAP@{N}:    {final_map:.5f}")
    print(f"nDCG@{N}:   {final_ndcg:.5f}")
    print(f"Recall@{N}: {final_recall:.5f}")
    
    return final_map, final_ndcg, final_recall

In [5]:
def evaluar_sasrec(ruta_csv_sasrec, test_df, N=10):
    test_dict = test_df.groupby('user_id')['item_id'].apply(list).to_dict()

    y_true = []
    y_pred = []

    sasrec = pd.read_csv(ruta_csv_sasrec)

    with open('SASRec.pytorch/python/data/mapa_usuarios.json', 'r') as f:
        diccionario_cargado = json.load(f)
    id2user_original = {int(k): int(v) for k, v in diccionario_cargado.items()}

    # Revertir el mapeo de usuarios
    sasrec['user_id'] = sasrec['user_id'].map(id2user_original)

    # Revertir el ajuste de ítems (restamos 1 a todas las columnas de rec_)
    for i in range(1, N + 1):
        sasrec[f'rec_{i}'] = sasrec[f'rec_{i}'] - 1

    sasrec_set = sasrec.set_index('user_id')

    for user_id_num, true_items in test_dict.items():
        if user_id_num in sasrec_set.index:
            row = sasrec_set.loc[user_id_num]
            lista_predicha = row[[f'rec_{i}' for i in range(1, N+1)]].tolist()
            
            if len(lista_predicha) > 0:
                y_true.append(true_items)
                y_pred.append(lista_predicha)

    map_score, ndcg_score, recall_score = evaluate_model(y_true, y_pred, N)
    
    return map_score, ndcg_score, recall_score

In [8]:
comparacion = pd.DataFrame(columns=["modelo", "map", "ndcg", "recall"])
map_clip, ndcg_clip, recall_clip = evaluar_sasrec(
    ruta_csv_sasrec="SASRec.pytorch/python/recomendaciones_sasrec_100.csv",
    test_df=test_df,
    N=10
)
comparacion.loc[0] = ["clip@10", map_clip, ndcg_clip, recall_clip]

map_clip_gated, ndcg_clip_gated, recall_clip_gated = evaluar_sasrec(
    ruta_csv_sasrec="SASRec.pytorch/python/recomendaciones_sasrec_gated_100.csv",
    test_df=test_df,
    N=10
)
comparacion.loc[1] = ["clip-gated@10", map_clip_gated, ndcg_clip_gated, recall_clip_gated]

map_siglip, ndcg_siglip, recall_siglip = evaluar_sasrec(
    ruta_csv_sasrec="SASRec.pytorch/python/recomendaciones_sasrec_siglip_100.csv",
    test_df=test_df,
    N=10
)
comparacion.loc[2] = ["siglip@10", map_siglip, ndcg_siglip, recall_siglip]

map_siglip_gated, ndcg_siglip_gated, recall_siglip_gated = evaluar_sasrec(
    ruta_csv_sasrec="SASRec.pytorch/python/recomendaciones_sasrec_siglip_gated_100.csv",
    test_df=test_df,
    N=10
)
comparacion.loc[3] = ["sglip-gated@10", map_siglip_gated, ndcg_siglip_gated, recall_siglip_gated]

Métricas de evaluación ranking (Top-10):
MAP@10:    0.00022
nDCG@10:   0.00086
Recall@10: 0.00205
Métricas de evaluación ranking (Top-10):
MAP@10:    0.00022
nDCG@10:   0.00068
Recall@10: 0.00144
Métricas de evaluación ranking (Top-10):
MAP@10:    0.00019
nDCG@10:   0.00062
Recall@10: 0.00129
Métricas de evaluación ranking (Top-10):
MAP@10:    0.00023
nDCG@10:   0.00081
Recall@10: 0.00171

In [9]:
display(comparacion)

           modelo       map      ndcg    recall
0         clip@10  0.000221  0.000857  0.002051
1   clip-gated@10  0.000222  0.000683  0.001443
2       siglip@10  0.000192  0.000615  0.001287
3  sglip-gated@10  0.000229  0.000810  0.001713

In [11]:
comparacion5 = pd.DataFrame(columns=["modelo", "map", "ndcg", "recall"])
map_clip, ndcg_clip, recall_clip = evaluar_sasrec(
    ruta_csv_sasrec="SASRec.pytorch/python/recomendaciones_sasrec_100.csv",
    test_df=test_df,
    N=5
)
comparacion5.loc[0] = ["clip@10", map_clip, ndcg_clip, recall_clip]

map_clip_gated, ndcg_clip_gated, recall_clip_gated = evaluar_sasrec(
    ruta_csv_sasrec="SASRec.pytorch/python/recomendaciones_sasrec_gated_100.csv",
    test_df=test_df,
    N=5
)
comparacion5.loc[1] = ["clip-gated@10", map_clip_gated, ndcg_clip_gated, recall_clip_gated]

map_siglip, ndcg_siglip, recall_siglip = evaluar_sasrec(
    ruta_csv_sasrec="SASRec.pytorch/python/recomendaciones_sasrec_siglip_100.csv",
    test_df=test_df,
    N=5
)
comparacion5.loc[2] = ["siglip@10", map_siglip, ndcg_siglip, recall_siglip]

map_siglip_gated, ndcg_siglip_gated, recall_siglip_gated = evaluar_sasrec(
    ruta_csv_sasrec="SASRec.pytorch/python/recomendaciones_sasrec_siglip_gated_100.csv",
    test_df=test_df,
    N=5
)
comparacion5.loc[3] = ["sglip-gated@10", map_siglip_gated, ndcg_siglip_gated, recall_siglip_gated]

display(comparacion5)

Métricas de evaluación ranking (Top-5):
MAP@5:    0.00016
nDCG@5:   0.00038
Recall@5: 0.00069
Métricas de evaluación ranking (Top-5):
MAP@5:    0.00022
nDCG@5:   0.00054
Recall@5: 0.00101
Métricas de evaluación ranking (Top-5):
MAP@5:    0.00017
nDCG@5:   0.00046
Recall@5: 0.00086
Métricas de evaluación ranking (Top-5):
MAP@5:    0.00021
nDCG@5:   0.00054
Recall@5: 0.00098

           modelo       map      ndcg    recall
0         clip@10  0.000160  0.000381  0.000690
1   clip-gated@10  0.000224  0.000543  0.001011
2       siglip@10  0.000166  0.000459  0.000856
3  sglip-gated@10  0.000208  0.000542  0.000978